### PR TITLE
Initiation of Audit Logging

### PR DESCRIPTION
**Pull request by BrianMejia**
**Related Issues**
This is in relation to #64 

**Describe the Changes**
I've added an external crate, [`flexi_logger`](https://github.com/emabee/flexi_logger), that allows us to use a macro that can log events that we specify to a file. A small example that involves adding group members to projects is included, once `audit_logger()` is called, any string passed to it will append to a file called `observatory_audit.log` in the `logs` directory. Example output would look like:

```
[2019-10-16 11:31:21.043672 -04:00] INFO [src/main.rs:209] Audit Logger Initialized!
[2019-10-16 11:31:49.337617 -04:00] INFO [src/groups/handlers.rs:204] User 0 has added User 2 to Group 1
```

**Still To Do**
There is an experimental feature that allows us to use a configuration file, a `specfile`. I need to figure out which parameters this file can take in, if they are at least equivalent to those configuration options in the code, then it should be feasible to use a config file.

Is the naming scheme suitable? The log file can only start with the module name the configuration is initialized from (for example `observatory` if the `FileLogWriter` is made in main), but having a discriminant should show some distinction in case we need multiple log files.

**Problems**
Given a global level of logging, any other log output would be suppressed if a log message does not match our config's filters. This could be a problem with initialization as the logging of fairings/handlers/etc. would not show. This is just something to keep in mind.

**Acknowledgements**
@rushsteve1 for suggesting we use a crate for logging.

### CODE REVIEW

**Comment by rushsteve1** [comment]
What made you choose `flexi_logger` specifically? I don't have any complaints, I'm just wondering why you chose it compared to a [`log`-based](https://crates.io/crates/log) crate?

**Comment by BrianMejia** [comment]
`flexi_logger` is in that list, but in comparison to the other simple loggers in that category, this package has support for easily writing to a file (which could lead into `.toml` configuration), multiple writers in case we need to separate log events for any reason, and the `Logger` class has a [robust](https://docs.rs/flexi_logger/0.14.4/flexi_logger/struct.Logger.html) set of configuration options.

A bonus is that it's [documented](https://docs.rs/flexi_logger/0.14.4/flexi_logger/) pretty well, aside from the `specfile` configuration, as that feature is pretty fresh.

**Comment by rushsteve1** [comment]
That sounds great! If you want to start putting in some logging for events then we can start talking about merging.

Does the specfile need to be present at runtime? Or only at compile time. We may need to embed it if it is needed at runtime?

**Comment by BrianMejia** [comment]
@rushsteve1 feel free to check out commit 69d908e, it should have what we were talking about earlier! Just have to pass the initial string and some arguments and then `format_args!` handles the rest.

**Comment by BrianMejia** [comment]
Also do macros like `println!` and `format_args!` do implicit referencing? The usual borrowing errors do not show up when I give the macros some variables of various types.

**Comment by rushsteve1** [comment]
This looks really good! The macro is clean and fixes the issue easily.

> Also do macros like `println!` and `format_args!` do implicit referencing? The usual borrowing errors do not show up when I give the macros some variables of various types.

As I understand it macros expand to their full version in-place. Meaning they don't take ownership like a function would, so they don't need to do referencing.

**Review by rushsteve1 — APPROVED** [review]

**Pull request merged**
